package com.cglia.student.entity;
// Generated Jun 9, 2023, 4:58:42 PM by Hibernate Tools 4.3.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * ProjectInformation generated by hbm2java
 */
@Entity
@Table(name = "project_information", catalog = "bhuvan")
public class ProjectInformation implements java.io.Serializable {

	private Integer projectId;
	private String projectName;
	private String spendTime;
	private Set<StudentInformation> studentsProjects = new HashSet<StudentInformation>(0);

	public ProjectInformation() {
	}

	public ProjectInformation(String projectName, String spendTime, Set<StudentInformation> studentsProjects) {
		this.projectName = projectName;
		this.spendTime = spendTime;
		this.studentsProjects = studentsProjects;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "project_id", unique = true, nullable = false)
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "project_name", length = 45)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "spend_time", length = 45)
	public String getSpendTime() {
		return this.spendTime;
	}

	public void setSpendTime(String spendTime) {
		this.spendTime = spendTime;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "students_project", joinColumns = { @JoinColumn(name = "project_id") }, inverseJoinColumns = {
			@JoinColumn(name = "student_id") })
	public Set<StudentInformation> getStudents() {
		return this.studentsProjects;
	}

	public void setStudents(Set<StudentInformation> students) {
		this.studentsProjects = students;
	}

}
