package com.cglia.student.entity;
// Generated Jun 9, 2023, 1:29:49 PM by Hibernate Tools 4.3.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * StudentResult generated by hbm2java
 */
@Entity
@Table(name = "student_result", catalog = "bhuvan")
public class StudentResult implements java.io.Serializable {

	private Integer resultId;
	private Integer math;
	private Integer english;
	private Integer hindi;
	private Integer science;
	private Long totalMark;
	private StudentInformation studentInformations = new StudentInformation();

	public StudentResult() {
	}

	public StudentResult(Integer math, Integer english, Integer hindi, Integer science, Long totalMark,
			StudentInformation studentInformations) {
		this.math = math;
		this.english = english;
		this.hindi = hindi;
		this.science = science;
		this.totalMark = totalMark;
		this.studentInformations = studentInformations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "result_id", unique = true, nullable = false)
	public Integer getResultId() {
		return this.resultId;
	}

	public void setResultId(Integer resultId) {
		this.resultId = resultId;
	}

	@Column(name = "math")
	public Integer getMath() {
		return this.math;
	}

	public void setMath(Integer math) {
		this.math = math;
	}

	@Column(name = "english")
	public Integer getEnglish() {
		return this.english;
	}

	public void setEnglish(Integer english) {
		this.english = english;
	}

	@Column(name = "hindi")
	public Integer getHindi() {
		return this.hindi;
	}

	public void setHindi(Integer hindi) {
		this.hindi = hindi;
	}

	@Column(name = "science")
	public Integer getScience() {
		return this.science;
	}

	public void setScience(Integer science) {
		this.science = science;
	}

	@Column(name = "total_mark")
	public Long getTotalMark() {
		return this.totalMark;
	}

	public void setTotalMark(Long totalMark) {
		this.totalMark = totalMark;
	}

	@JsonIgnore
	@OneToOne(fetch = FetchType.LAZY, mappedBy = "studentResult")
	public StudentInformation getStudentInformations() {
		return this.studentInformations;
	}

	public void setStudentInformations(StudentInformation studentInformations) {
		this.studentInformations = studentInformations;
	}

}
