package com.cglia.student.entity;
// Generated Jun 9, 2023, 1:29:49 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * StudentInformation generated by hbm2java
 */
@Entity
@Table(name = "student_information", catalog = "bhuvan")
public class StudentInformation implements java.io.Serializable {

	private int studentId;
	private StudentResult studentResult;
	private String studentAge;
	private String studentEmail;
	private String studentGender;
	private String studentName;
	private Set<StudentAddress> studentAddresses = new HashSet<StudentAddress>(0);

	public StudentInformation() {
	}

	public StudentInformation(int studentId) {
		this.studentId = studentId;
	}

	

	public StudentInformation(int studentId, StudentResult studentResult, String studentAge, String studentEmail,
			String studentGender, String studentName, Set<StudentAddress> studentAddresses) {
		super();
		this.studentId = studentId;
		this.studentResult = studentResult;
		this.studentAge = studentAge;
		this.studentEmail = studentEmail;
		this.studentGender = studentGender;
		this.studentName = studentName;
		this.studentAddresses = studentAddresses;
	}

	@Id
	@Column(name = "student_id", unique = true, nullable = false)
	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	@OneToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "result_id")
	public StudentResult getStudentResult() {
		return this.studentResult;
	}

	public void setStudentResult(StudentResult studentResult) {
		this.studentResult = studentResult;
	}

	@Column(name = "student_age")
	public String getStudentAge() {
		return this.studentAge;
	}

	public void setStudentAge(String studentAge) {
		this.studentAge = studentAge;
	}

	@Column(name = "student_email")
	public String getStudentEmail() {
		return this.studentEmail;
	}

	public void setStudentEmail(String studentEmail) {
		this.studentEmail = studentEmail;
	}

	@Column(name = "student_gender")
	public String getStudentGender() {
		return this.studentGender;
	}

	public void setStudentGender(String studentGender) {
		this.studentGender = studentGender;
	}

	@Column(name = "student_name")
	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studentInformation")
	public Set<StudentAddress> getStudentAddresses() {
		return this.studentAddresses;
	}

	public void setStudentAddresses(Set<StudentAddress> studentAddresses) {
		this.studentAddresses = studentAddresses;
	}
}
